import 'package:cached_network_image/cached_network_image.dart';
import 'package:flutter/material.dart';
import 'package:flutter_gen/gen_l10n/app_localizations.dart';
import 'package:intl/intl.dart';
import 'package:octo_image/octo_image.dart';
import 'package:provider/provider.dart';
import 'package:ultimate_bundle/premium/belila/src/helpers/colors.dart';
import 'package:ultimate_bundle/premium/belila/src/helpers/constants.dart';
import 'package:ultimate_bundle/premium/belila/src/helpers/screens.dart';
import 'package:ultimate_bundle/premium/belila/src/helpers/toast.dart';
import 'package:ultimate_bundle/premium/belila/src/models/chat_message_model.dart';
import 'package:ultimate_bundle/premium/belila/src/models/chat_model.dart';
import 'package:ultimate_bundle/premium/belila/src/widgets/custom_app_bar.dart';
import 'package:ultimate_bundle/providers/theme_provider.dart';

part 'screens/chat_screen.dart';
part 'widgets/bubble_chat.dart';
part 'widgets/build_product_list_tile.dart';
part 'widgets/build_send_text_field.dart';
